### ISSUE TITLE
cannot start docker container

### ISSUE THREAD

**Issue by otto2me** [agarbato/unicloud#8]
Hi,

I like to use your project, as I know how tricky unison is to use. However, I have the issue that neither on Windows nor on my Synology NAS I can start the container, i get this error:

http.client.InvalidURL: nonnumeric port: 'None'
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
  File "/usr/lib/python3.8/http/client.py", line 876, in _get_hostport
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python3.8/http/client.py", line 833, in __init__
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    response = urlopen(status_url)
  File "start.py", line 51, in api_check
    print (api_check())
  File "start.py", line 297, in <module>
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

ValueError: invalid literal for int() with base 10: 'None'
    port = int(host[i+1:])
  File "/usr/lib/python3.8/http/client.py", line 871, in _get_hostport
Traceback (most recent call last):
Checking Server API Status
Creating Supervise Config

Any Idea what the problem could be?

**Comment by agarbato** [comment]
Hi @otto2me ,

Thanks for testing the project.
It seems that you didn't pass some mandatory env parameters to your client container.

`    - API_PROTOCOL=http
      - API_PORT=80`

How are you trying to start the containers? docker-compose?

You need at least a server and a client.

Can you check the [docker-compose.yml](https://raw.githubusercontent.com/agarbato/unicloud/main/docker-compose.yml) example and make sure to pass all env vars?

Please share your docker run or compose so I can help you to understand what's missing.
Thanks
Andrea

**Comment by agarbato** [comment]
Closing issue as there's no way to debug due to missing information and no feedback received.
